version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "📦 Installing dependencies..."
      - cd vite-app
      - npm install

  build:
    commands:
      - set -e # Exit on error
      - echo "⚙️ Building Vite React App..."
      - npm run build

  post_build:
    commands:
      - echo "📂 Moving build output to top-level dist/"
      - cd ..
      - mkdir -p dist
      - cp -r vite-app/dist/* dist/

artifacts:
  files:
    - dist/**/*
    - appspec.yml
    - scripts/**/*


