version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin <aws_account_id>.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - docker build -t devops-demo .
      - docker tag devops-demo:latest <aws_account_id>.dkr.ecr.ap-south-1.amazonaws.com/devops-demo
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push <aws_account_id>.dkr.ecr.ap-south-1.amazonaws.com/devops-demo

artifacts:
  files:
    - '**/*'
