
name: Deploy to EC2 using CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install & Build
      working-directory: vite-app
      run: |
        npm install
        npm run build

    - name: Zip App
      run: |
        chmod +x scripts/*.sh
        zip -r vite-app.zip appspec.yml scripts/ vite-app/

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Upload to S3
      run: |
        aws s3 cp vite-app.zip s3://${{ secrets.S3_BUCKET }}/vite-app.zip

    - name: Trigger CodeDeploy
      run: |
        aws deploy create-deployment \
          --application-name vite-react-app \
          --deployment-group-name vite-react-group \
          --s3-location bucket=${{ secrets.S3_BUCKET }},bundleType=zip,key=vite-app.zip \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --description "GitHub Actions Deployment"
